USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS HL7 COMMENT = 'HL7 FHIR Database';
CREATE SCHEMA IF NOT EXISTS HL7.RAW;

CREATE WAREHOUSE IF NOT EXISTS HL7_FHIR_WH
    WAREHOUSE_SIZE = 'SMALL'
    INITIALLY_SUSPENDED = TRUE
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
